name: Update Streak Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download Streak Stats Image
        run: |
          # We use the main server (demolab) which is most reliable for downloads
          curl -L --retry 3 --fail -o github-streak-stats.svg "https://streak-stats.demolab.com/?user=FarhanSayed16&theme=tokyonight&hide_border=true&background=0D1117"

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update streak stats
          file_pattern: github-streak-stats.svg
